# ---------------------Deployment---------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask # name of the deployment
  labels:
    name: flask # label used to identify the deployment
# ---------------------ReplicaSet---------------------------------
spec:
  replicas: 3 # define the number of pods to run
  selector:
    matchLabels:
      app: flask
  # ---------------------Pod----------------------------------------
  template:
    metadata:
      labels:
        app: flask # label used to identify the pod
    spec:
      containers:
        - name: my-python-app
          image: registry.digitalocean.com/si-k8s-registry-leo/my-python-app
      restartPolicy: Always
